### ISSUE TITLE
not a issue

### ISSUE THREAD

**Issue by thapakazi** [sandipbgt/ntc-websms#1]
thanks for making it public. :bow: 

Can I send more than 10 sms in a day ? :stuck_out_tongue: 
Sucessfully sent my sms:
### Installation:

```
 sudo pip install lxml ntc-websms
..some warning msg...                                                                                                     
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python3.5/site-packages
Collecting ntc-websms
  Downloading ntc-websms-0.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3.5/site-packages (from ntc-websms)
Collecting argparse (from ntc-websms)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: argparse, ntc-websms
  Running setup.py install for ntc-websms ... done
Successfully installed argparse-1.4.0 ntc-websms-0.1.0
```

And then source ~/.meet_credentials &&
![screenshot-20160708-11 58 24](https://cloud.githubusercontent.com/assets/1695906/16678905/6d7fceb4-4503-11e6-9d63-31799a71f365.png)

Nice and Handy, Now I can make use of my contact list :neckbeard:

**Comment by sandipbgt** [comment]
Thanks for trying. 
Regarding your query, you can send only 10 sms per day since it is the limit set my NTC.

**Comment by shivapoudel** [comment]
@sandipbgt Since mine question is not about the exact issue, not opening new one. Since I am a dumb at Python snake (just kidding), could you extend the future of it in node architecture also. It will be much helpful for developers like me who keeps cell phones away during working hours and stick to CLI all day chatting with commands. Just kidding and asking if you got time and is possible to create a node package xD

**Comment by sandipbgt** [comment]
@shivapoudel Since, it's a command line tool, it makes no difference whether it is written in Python or Node. Anyway, if you need help in setting up Python environment, I can help. In future, I may port it to Node as well.

**Comment by shivapoudel** [comment]
> In future, I may port it to Node as well.

@sandipbgt This hope already works great for me. Thanks :D
